-- INSERT INTO `singers_contests`.`users`
-- (`id`, `first_name`, `last_name`, `middle_name`, `email`, `password`, `username`, `phone_number`)
-- VALUES (1, 'Nikolay', 'Kostadinov', 'Dimitrov', 'kostadinov.nikolay.d@gmail.com',
--         'bf92978758a05b5cc483737e416df897f3a657a4571ea343e863f49395f7fa87ba4d35cd734044ca', 'niki', '+359 886 630 111');
-- insert into `singers_contests`.`contests` (id, name)
-- values (1, 'Silver Yantra'),
--        (2, 'Flower tuning fork'),
--        (3, 'Sarandev'),
--        (4, 'River notes'),
--        (5, 'Danube stars'),
--        (6, 'Fifteen tulips'),
--        (7, 'The road to the stars'),
--        (8, 'Artship Festival Pomorie'),
--        (9, 'Art Stars'),
--        (10, 'Coast Happiness'),
--        (11, 'Abanico'),
--        (12, 'Sofia Grandprix'),
--        (13, 'Tallents Of Tomorrow'),
--        (14, 'Bravo festival'),
--        (15, 'Slavic bazaar in Vitebsk'),
--        (16, 'Song pallet')
-- ;
